title:  Toast Tips
tagline:  A handy guide to making loaf

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-28662509-3'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}

social:
- {icon: 'envelope', link: 'mailto:toastips.com@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
